# Generated by Django 5.0.1 on 2024-01-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
